id: PCFA9A603
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG4526
  instance_id: http://purl.bdrc.io/resource/IE1KG4526
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - རྒྱུན་གྱི་ཁ་འདོན་བཅུད་བསྡུས་དང་ཕུན་སུམ་ཚོགས་པའི་བཞུགས་གྲལ་གྱི་རིམ་པ།
  alt_title: {}
  author: None
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    3e4eb6f41af5430b92ae699f9a680cfe:
      title: པོད ༡་རྒྱུན་གྱི་ཁ་འདོན་བཅུད་བསྡུས་དང་ཕུན་སུམ་ཚོགས་པའི་བཞུགས་གྲལ་གྱི་རིམ་པ
      volume_number: 1
      base_file: UT1KG4526_I1KG4549_0000.txt
      reference: http://purl.bdrc.io/resource/VLA1528A8F74399752
      image_group: I1KG4549
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG4526
  - http://purl.bdrc.io/resource/MW1KG4526
  ocr_software: Namsel
created_at: '2021-12-22T10:42:29.893339'
last_modified_at: '2021-12-22T10:42:29.893345'
statistics:
  total_words: 15704
  total_non_words: 2430
quality:
  non_words_ratio: 0.15
